### ISSUE TITLE
Deconvolved source sizes

### ISSUE THREAD

**Issue by lmorabit** [mhardcastle/lgz#10]
The current catalogue has source sizes convolved with a 6 arcsecond beam. It would be great to get the deconvolved sizes to use for conversion to proper linear sizes.

**Comment by mhardcastle** [comment]
Deconvolved sizes can be calculated from the non-deconvolved sizes; crudely:

```
deconv=t['Maj']**2.0-6.0**2.0
size=np.where(deconv>0, np.sqrt(deconv), 0)
```

I sort of agree that these shouldn't have been removed from the original pybdsf catalogues though. @twshimwell, any reason why you took them out? (These are DC_Maj etc.)

**Comment by twshimwell** [comment]
Nope no reason. I have them all for the individual mosaics so I can easily make a new catalogue with deconvolved sizes if its something we want.

**Comment by mhardcastle** [comment]
Let's do that then for the next release.

**Comment by mhardcastle** [comment]
(Obviously the deconvolved sizes for the non-Gaussian and LGZ sources are kind of poorly defined anyway: for LGZ we don't really have a proper size measurement at all yet.)

**Comment by lmorabit** [comment]
Right, LGZ will clearly be different.  The pybdsf deconvolved sizes for the single-gaussian sources would be a huge help at the moment (that's what most of my sample seems to be anyway), but obviously at some point I'd like the sizes measured for LGZ things. I was thinking this might make a nice summer student project? If that's an appropriate timescale. The student could look at automating a way to measure LGZ sizes, and extend the unification project I did for Bootes to the HETDEX area.

**Comment by mhardcastle** [comment]
Beatriz is already working on code to do automatic size measurements for LGZ. @jcroston may want to comment...

**Comment by jcroston** [comment]
@lmorabit Hi Leah, yes, Beatriz's code does this - we are currently running it on all sources with catalogue size > 8.5 arcsec (corresponding to ~6" deconvolved), which will include all the LGZ sources. Our method catches all emission above some sigma threshold that is within, or connected to, any components associated with the particular source, and outputs a (deconvolved) size that corresponds to the largest extent of this emission (it also calculates what should be a more accurate flux from the same associated emission). There are still a few issues to be ironed out related to the fainter extended sources, but the method works well for the LGZ sources, and we should have an updated set of sizes based on the current optical ID catalogue in the next few days. I can keep you posted about this if you'd like - there's definitely room to discuss alternative approaches for the size measurements (I think @wllwen007 was doing something a little different for the H-ATLAS dataset) but our existing machinery makes it fairly easy to try different things with the LGZ multi-component sources.

**Comment by lmorabit** [comment]
@jcroston That's great. Yes, I'd like to be kept in the loop. Are you looking to include these in the data release?

**Comment by mhardcastle** [comment]
Deconvolved source sizes now in v0.4 of the catalogue. Closing this, reopen if there's still a problem.
