### ISSUE TITLE
ID flags in the current value added catalogue

### ISSUE THREAD

**Issue by jcroston** [mhardcastle/lgz#11]
The current ID_flag value aren't consistent with the documentation for the optical catalogue (e.g. what are 311, 312, etc?) Please could the documentation be updated to explain what these are.

**Comment by wndywllms** [comment]
I've updated these on the [wiki](http://lofar.strw.leidenuniv.nl/wiki/doku.php?id=hetdex_catalog_description#id_flag_codes):

ID_flag Codes
1 - identification from maximum likelihood analysis
2 - match to a bright galaxy (either 2MASX or SDSS)
3?? - identification from LGZ, second digit is version number, third digit is further flag, (fourth digit is output pending)
311 - output from LGZv1
312 - output from LGZv1 (too-zoomed-in)
322 - output from LGZv2 (direct to too-zoomed-in)
3210 - output from LGZv2 (pending)
3220 - output from LGZv2 (direct to too-zoomed-in - pending)
4 - no identification possible
5 - identification method TBD

**Comment by mhardcastle** [comment]
Closing.

**Comment by jcroston** [comment]
Thanks Wendy!
