### ISSUE TITLE
2MASS sources missing LGZ_Assoc_Qual and LGZ_ID_Qual

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/lgz#18]
As these ID_flag==2 sources appear like LGZ sources in other respects they should probably have quality flags -- otherwise we run the risk of them being filtered by accident.

**Comment by wndywllms** [comment]
I've given them flags of 1

fixed in c7368f729057a5a9c37d4aa95d1f5f7d6f2c2002
