### ISSUE TITLE
LGZ_Assoc is 0 instead of 1 for single component LGZ sources

### ISSUE THREAD

**Issue by wndywllms** [mhardcastle/lgz#19]
LGZ_Assoc (or Assoc in process_lgz) is set to 0 for LGZ sources with only one component. Should be 1 for consistency.

**Comment by mhardcastle** [comment]
This is @jcroston's convention and I stuck with it for consistency. I agree it would be a lot better (and simpler to code!) if it were as you say.

**Comment by jcroston** [comment]
Yes, I agree this doesn't really make sense any more -it's leftover from when I had a different format of components table and used the column as a yes/no for whether the source had entries in it. I'm happy to fix this in the LGZ code (and/or in the meantime for next catalogue version just to switch the 0s to 1s).

**Comment by mhardcastle** [comment]
I can fix this in the process_lgz code for now: it recalculates all of these anyway.

**Comment by mhardcastle** [comment]
Fixed in 6a27322.
