### ISSUE TITLE
Incorrect RA,Dec reported for some sources in value-added catalogue 

### ISSUE THREAD

**Issue by jrcallingham** [mhardcastle/lgz#21]
I think there is an issue with some sources having incorrect RA, Dec reported in the value added catalogue. I am assuming the RA and DEC columns reported in the value-added catalogue should be identical to the radio only catalogue (i.e. it is not updated).

For example, I am comparing the position reported for ILTJ112416.41+513338.5 in LOFAR_HBA_T1_DR1_merge_ID_optical_v0.6.fits and LOFAR_HBA_T1_DR1_catalog_v0.9.srl.fixed.fits. Below is the snapshot of where the RA and DEC reported in the value-added catalogue is indicated by the cross-hair. This is approximately ~30" from the radio source (and the reported position in the radio-only catalogue is right on top of the source).

![image](https://user-images.githubusercontent.com/7263019/35043723-ee4b2e3e-fb8d-11e7-910c-57a6c861b7cc.png)

I didn't think the RA/DEC columns should be changed at all between the catalogues but you might be trying to report the centre of some FRIIs? Clearly something is amiss with this source. There are several sources like this but not as extreme (e.g. ILTJ150049.52+475105.3 and ILTJ124833.80+512800.1).

PS Just talked to Ken Duncan and he thinks Leah Morabito is also seeing something similar?

**Comment by mhardcastle** [comment]
OK, I know what's happening here. We're now recomputing the positions of all LGZ sources from their component list to fix different some inconsistencies in the previous version of the catalogue. Sources like this that are composed of multiple components get the mean RA and DEC of their components. But those means should be the flux-weighted means, and they're not. Going to a flux-weighted mean should fix this, though it's possible it will cause problems for other sources. There is really no right answer to the question of what the position is in general, but I don't think we have the optimal one at the moment.

**Comment by jrcallingham** [comment]
That makes sense for some of the cases. However, with this source, I don't quite get why the position is so distant from any radio emission? So you are implying that some faint radio emission more than 30" are is being associated with this source, and then you are averaging the positions? 
If so, flux weighted mean would likely fix this issue but I have no appreciation how this would change other things. Do you have to update the RA/DEC columns since you merge sources in the value-added catalogue?

**Comment by wndywllms** [comment]
> I didn't think the RA/DEC columns should be changed at all between the catalogues but you might be trying to report the centre of some FRIIs? 

Yes, the positions do and *should* get changed (albeit with the caveats @mhardcastle mentioned about what this actually means in terms of a flux-weighted centre or not -- I'm actually using a flux-weighted centre when I merge the 2MASX sources so we should at least be consistent)

FYI The component catalogue will tell you what component pybdsf (radio-only) sources went into the final merged source - they will have the same New_Source_Name as the Source_Name in the merged catalogue, so from that you can see the two components of this source are ILTJ112413.12+513349.7 and ILTJ112419.71+513327.3 (the bright one and a faint 65"-distant companion 51" in size  which by the wisdom of LGZ are part of the same source)

**Comment by jrcallingham** [comment]
Agreed Wendy that you should update the positions as long as you report the components (which, as you indicate, you do). If I squint I can some relic emission that could be associated with this source that likely led the LGZ to classify them together. However, I think for the way people will use the catalogue once it is public, the current reported position is not right. The flux-weighted centre is the way to go.

**Comment by mhardcastle** [comment]
Fixed by 74d449934e8ddec094b7017edc297832af6a262d.

Flux-weighting for this composite source turns it into ILTJ112413.54+513348.3 which is much closer to the bright source.

Closing this for now, please check in the next catalogue version and re-open if necessary.
