### ISSUE TITLE
Components with bad DEC values

### ISSUE THREAD

**Issue by bmingo** [mhardcastle/lgz#24]
There seem to be 93 entries in the v0.8 components catalogue with bad DEC values (DEC=-90.). Most of them seem to have been flagged as artefacts, but not all.

I have saved the relevant rows on a directory in the LOFAR server:
/data/lofar/bmingo/tests/v0.8_comp_bad_DEC.fits

EDIT: while some of the sources seem to have artefact_flag=FALSE, they all seem to belong to the Artefact_flag subset

**Comment by bmingo** [comment]
Apologies, another addition (I thought it might be safer to post as a response, in case you don't see the edits).

I have just realised that there are two artefact flags: column 40=artefact_flag (~50% of the components mentioned have this =TRUE) and column 64=Artefact_flag (all the components mentioned have this =TRUE, hence, I assume, why they are in the Artefact_flag subset)

**Comment by wndywllms** [comment]
Yup, I'm aware of this and already fixed the -90 dec problem. It was supposed to be a temporary step to compute the distance to the nearest non-artefact, but I ended up changing the table and not a copy of the column.  Artefacts are actually removed from the component list now, but there are a few where artefacts identified in the flowchart are associated to an LGZ source and so are included in the component catalogue.

**Comment by wndywllms** [comment]
incidentally the component catalogue still has loads of extra columns which should be trimmed down (and documented). Artefact_flag is the union of all flags indicating an artefact (incl artefact_flag, the rest are more complex visual classification flags).

**Comment by mhardcastle** [comment]
Closing this issue since I guess it's fixed in the v0.7 catalogue release. We should open a new issue for documentation.
