### ISSUE TITLE
Tidy up the component catalogue

### ISSUE THREAD

**Issue by wndywllms** [mhardcastle/lgz#25]
We need to decide what columns to keep in the component catalogue and document them.

**Comment by wndywllms** [comment]
The trimmed list of columns (descriptions mostly as for the source catalogue):

Source_Name
RA
E_RA
DEC
E_DEC
Peak_flux
E_Peak_flux
Total_flux
E_Total_flux
Maj
E_Maj
Min
E_Min
DC_Maj
E_DC_Maj
DC_Min
E_DC_Min
PA
E_PA
DC_PA
E_DC_PA
Isl_rms
S_Code
Mosaic_ID
Isl_id
Number_Masked
Number_Pointings
Masked_Fraction
Ng   (number of gaussians)
ID_flag   (as for the source catalogue, but records the flags for each component)
New_Source_Name

Not including the artefact flags because artefacts shouldn't be included. Most of the other columns are for various internal calculations/flags.

Anything obviously missing?

**Comment by wndywllms** [comment]
I would suggest changing 
Source_Name -> Component_Name  (matches to the PyBDSF Source or Gaussian catalogues as appropriate)
New_Source_Name -> Source_Name   (since this matches to Source_Name in the Source catalogue)

**Comment by bmingo** [comment]
I'd be happy with that! 
Is there a "near a bright source" flag among the internal ones? If so, it may be worth keeping those (even if the component is not an artefact, it would warn the users to be careful about local rms, etc.)

**Comment by wndywllms** [comment]
> Is there a "near a bright source" flag among the internal ones? If so, it may be worth keeping those (even if the component is not an artefact, it would warn the users to be careful about local rms, etc.)

Would be nice, but bright star masking/flagging is still an open issue (https://github.com/mhardcastle/lotss-catalogue/issues/3)

EDIT: oh you mean near bright radio source (duh)

**Comment by wndywllms** [comment]
> Is there a "near a bright source" flag among the internal ones? If so, it may be worth keeping those (even if the component is not an artefact, it would warn the users to be careful about local rms, etc.)

to answer your actual question: there is not currently such a flag. I agree it could be useful, but we'd have to define 'how near is near', 'how bright is bright'...

**Comment by mhardcastle** [comment]
Of course Isl_rms would give some indication of this.

**Comment by mhardcastle** [comment]
Beatriz's request is an enhancement; the basic issue here will be fixed in the latest catalogue, so closing this.
