### ISSUE TITLE
column 'Mosaic_ID' correct information?

### ISSUE THREAD

**Issue by lmorabit** [mhardcastle/lgz#27]
I'm looking at LOFAR_HBA_T1_DR1_merge_ID_optical_v0.4.fits and it seems that somehow the column 'Mosaic_ID' is not properly catching the Mosaic_ID -- some are fine, with P214+55 but then there are columns where it's just 'P10Hetde' or 'P1Hetdex1' ... what's going on here?  Is there a standard format that we should be following for the mosaic IDs or are they listed somewhere that's accessible?

**Comment by twshimwell** [comment]
The P10Hetde or P1Hetdex1 (these are truncated which I thought we had fixed...) are the pointing names in the LTA. The naming convention was changed after cycle two to e.g. P214+55 which explains the mix. I'd have thought best to leave the LTA names (not truncated though)

**Comment by mhardcastle** [comment]
Yes, this is the result of truncation of this field in @twshimwell's original catalogue (I think it is still truncated but less so in more recent versions -- which means we have a mix in the final catalogue depending on where the data came from, e.g. there is both 'P10Hetde' and 'P10Hetdex'.

I worked round this so long ago that I guess I forgot it was an issue!

**Comment by twshimwell** [comment]
Ah, I thought I had fixed the truncation now.

**Comment by lmorabit** [comment]
So will it get updated in the next version of the catalogue? I think Catherine is trying to use this information for her project.

**Comment by mhardcastle** [comment]
I think you're still a couple of characters off, Tim (but we should check what we're using).

What we have is almost always enough to identify the mosaic without using the RA, Dec...

Leah: yes we should update in the next version. Thanks for pointing it out.

**Comment by mhardcastle** [comment]
(For what I do I have code that just makes a subimage from the required mosaic which it finds by going through RA, Dec and ignoring this field altogether. Maybe that doesn't work for Catherine though.)

**Comment by twshimwell** [comment]
yeh indeed my names are truncated. For the Hetdex names do you want e.g.

P11Hetdex12 or just P11Hedex

There is also just P6 which doesnt have Hetdex in the name. Should I just leave that as P6

**Comment by halecatherine** [comment]
I was trying to work out which sub-mosaic each source was in and extract some pixel values at its position, so I can write a wrap around to convert from the truncated Mosaic_ID to ###-mosaic.fits.

I think maybe if you are using the P11Hetdex12  name in the mosaic images/rms maps etc it might be  better using P11Hetdex12  that P11Hetdex but that is just my opinion.

**Comment by twshimwell** [comment]
OK, ill remake the catalogue with the names that match the mosaic images.

**Comment by mhardcastle** [comment]
I agree with Catherine that we should use the names that correspond to the image names. And since we have already released the images we are stuck with any slight inconsistencies in naming at this point...

Tim, can you let me know when you have the new merged pybdsf catalogue because there are several outstanding issues that depend on using it.

Catherine, the code in this repository `utils/get_fits.py` (specifically the last 4 lines or so and the LofarMaps class it imports) will get you a subimage at any given RA and Dec by directly parsing the FITS headers of the mosaic images (assuming you have a complete download of all of them).

**Comment by twshimwell** [comment]
ive sent it over.

**Comment by twshimwell** [comment]
The ones I just sent dont have the masked fraction (and other columns i appended) so im just adding that in.

**Comment by twshimwell** [comment]
ok ive sent the new one. Let me know if any issues. I've checked that all values in all the columns are  the same (besides Mosaic_ID where only 172311 entries are the same)

**Comment by mhardcastle** [comment]
Should be fixed in next release.
