### ISSUE TITLE
Strange bad pixels in P196+55

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/lgz#29]
There are odd individual pixels or collections of 2-3 pixels which have odd values in the P196+55 mosaic (most obvious towards the NW). I have been aware of this for a while but haven't got around to looking at FITS images and tracking down an actual location. This noise can't (I think) be a result of deconvolution -- it must appear in mosaicing. We ought to track it down. Fortunately I don't think it is likely to affect the cataloguing much.

**Comment by twshimwell** [comment]
Yeh we have seen this type of thing before but ill have to try to remember how we got rid of it.

I think in the mosaicing the weight map for L241961 is the issue (attached image of that map).

<img width="452" alt="screenshot 2018-02-04 08 48 39" src="https://user-images.githubusercontent.com/12065270/35775415-6b12066a-0988-11e8-9029-698b1ba71721.png">

**Comment by twshimwell** [comment]
The mosaics for P200+55 and P34Hetdex06 also seem to have this issue with the same pointing. For some reason the other 4 mosaics this pointing is in dont show weight maps like this, I guess this means its related to the reprojection somehow.

**Comment by mhardcastle** [comment]
Yep, that would do it.

First thing to try would be to remake the mosaic and see if the weight map is the same... in case anything's changed...

**Comment by twshimwell** [comment]
And fixed by simply remaking. That was easier than anticipated.

I'll remake the 3 mosaics that have this issue.

Do we want to redo the catalogues for these three mosaics too?

**Comment by mhardcastle** [comment]
We really don't want to mess with the catalogue at this stage.

I guess what we should do is make the catalogues for these and compare them with the originals -- if (as I suspect) there isn't much difference then we can live with the version we have.

(It'll also affect your noise plots and such-like things I suspect.)

**Comment by twshimwell** [comment]
There is some difference between the catalogues but perhaps its tolerable. For example, in the previous catalogue for P200+55 there were 7062 sources and 8194 components. Now there are 6930 sources and 8066 components. If I cross match the sources in both catalogues within 1arcsec then I get 6580 sources. Of these 6086 are "S' sources and the ratio of e.g. the peak fluxes of these sources is shown below.

![screenshot 2018-02-05 14 41 21](https://user-images.githubusercontent.com/12065270/35807311-a4b15970-0a82-11e8-87c1-61bbff849f54.png)

**Comment by mhardcastle** [comment]
I think that's tolerable. It's going to have to be unless we do something complicated like merging new fluxes into the old catalogue list. Changing source positions or sizes will break LGZ outputs.

**Comment by mhardcastle** [comment]
Tim, if you can put the new mosaics and other products like residual maps somewhere I can get them then I will upload on the data release site and we can close this issue.

**Comment by mhardcastle** [comment]
Updated data from Tim now on the release site. Closing this.
