### ISSUE TITLE
catalogued 14 degree source...

### ISSUE THREAD

**Issue by jcroston** [mhardcastle/lgz#31]
@bmingo has flagged up a strange catalogue entry. Source ILTJ114824.92+551438.2 has an LGZ_Size of around 13.6 degrees. Its central coordinates aren't within the mosaic that is listed for it in the catalogue. Its optical ID is a long way away from the central coordinates. 

It has an ID_Flag of 31 suggesting LGZv1, but it doesn't exist in earlier versions of the catalogue (I looked at version 0.6 as that's one we've processed previously - there is neither a source of that name, or anything with such a large size). @mhardcastle or @wllwen007 do you have any idea what can have happened here? Obviously it's only one source, but would be good to know what's happened in case it's flagging up a wider bug. (I have checked and there aren't any other ridiculously large sources).

**Comment by wndywllms** [comment]
well, it's got 2 components are separated by about 13 deg!
ILTJ112632.40+555443.6 ILTJ114824.92+551438.2 1
ILTJ125957.20+530331.9 ILTJ114824.92+551438.2 1
I think both of them were in LGZv1 (both are large and bright). 
@mhardcastle I guess something has gone wrong in the lgz processing to associate these 2 components (that weren't associated before)

**Comment by jcroston** [comment]
Thanks - I've checked the three catalogues generated by my initial LGZ output processing and there are no sources with the parent source name in any of them, or any sources with such a large size. So I think the association must have somehow arisen in the later processing.

The first listed component doesn't seem to be in any of the LGZ output catalogues with that name (possible it was LGZv1 and there was some later renaming for consistency?). The second component ILTJ125957.20+530331.9 is in the LGZv3 catalogue, but with no associations (it's not in LGZv2, which suggests it was one of the final set that went to LGZ after the flow-chart was rerun). It did have a blend probability of 0.2, but I'm not sure if that's high enough to have sent it to Martin's deblending. I think that despite the ID flag, something must have happened by accident in the final fixing up of awkward things. I'm not sure why the ID flag doesn't reflect that if so, but hopefully this means it's a one-off mistake and not indicative of any wider problem!

**Comment by mhardcastle** [comment]
It's probably a too-zoomed in correction file gone crazy. I'll try to track it down.

**Comment by mhardcastle** [comment]
This appears to have been a glitch in the LGZ v3 output. Will be fixed in the next catalogue release.

**Comment by bmingo** [comment]
Thank you!
Is only that one source affected by the glitch?

**Comment by mhardcastle** [comment]
So I'm told...

**Comment by jcroston** [comment]
Yes, pretty sure no other sources affected. There was one rogue click in the Zooniverse output for LGZv3 that was an interloper from LGZv1. It should have been filtered out, but ended up producing a source with non-matching name and coordinates that was sent down a component-matching pathway aimed at the annoying LGZv1 subset made from the early source catalogue, which led to odd results. There are no other rogue clicks in the LGZ input, and Martin has checked that no other components took this pathway through his code.

**Comment by mhardcastle** [comment]
Fixed in the soon-to-be-released v1.1.
