### ISSUE TITLE
Linking PyBDSF sources to optical catalogue sources

### ISSUE THREAD

**Issue by nudomarinero** [mhardcastle/lgz#33]
As we understand, the "Source_Name" in the optical source catalogue (OSC) is a final source name that in some cases corresponds to the original PyBDSF "Source_Name". However, in some cases the "Source_Name" is new (one PyBDSF source may be split in several OSC sources or many PyBDSF sources may be combined in a single OSC source) and there is no way to match the sources between catalogues.
It would be nice to have a table with the correspondence between sources in the two catalogues (like a many to many relationship; https://en.wikipedia.org/wiki/Many-to-many_(data_model))

**Comment by mhardcastle** [comment]
This is what the component catalogue is for. 'Component_Name' in this catalogue corresponds to the original PyBDSF catalogue (in most cases except blends). 'Source_Name' corresponds to the source in the OSC.

**Comment by mhardcastle** [comment]
We agreed that we should produce a list of sources flagged as artefacts: then it's possible to distinguish between sources that are deblended and sources that are artefacts without having to create an entire new catalogue just for this.

We could also add a 'Deblended_from' column in the components list when doing the deblending.

**Comment by mhardcastle** [comment]
The new v1.1 components catalogue has a `Deblended_From` field which is set if and only if the component it refers was promoted from being a Gaussian component of the named PyBDSF source. So I think that part is done.

Discussion in e-mail seems to have come to the consensus that a further annotated catalogue was required to label the artefacts (and this could also list the sources destroyed by deblending, at the risk of creating another opportunity for inconsistency!) so I guess we should keep this open. Could still be an extra product for the 1.1 release.

**Comment by mhardcastle** [comment]
Superseded by developments in the deep fields code.
