### ISSUE TITLE
spectroscopic redshifts

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/lgz#35]
When I download redshifts from SDSS DR14 I find a bunch of sources in the final catalogue (888 of them in total) that have a warning-free spectroscopic redshift in DR14 but no z_spec in our catalogue. These don't seem to be particularly different from the existing spec-zs (see image).

I understand that Joe may have some extra spec-zs too.

I guess what we want to do is insert these into Ken's catalogue -- there may be reasons to exclude these sources from the training set but we probably want them in the final output, and we want the rest-frame magnitudes to be correct for the spec-zs. Comments anyone?
![redshifts](https://user-images.githubusercontent.com/5337708/37775194-31b8a42a-2dda-11e8-95dd-efd3c82406c7.png)

**Comment by djbsmith** [comment]
I think we probably do want the extra redshifts, but we probably also need to worry about where they come from and how reliable they are. With SDSS this is easy to assess, but for redshifts found elsewhere (e.g. on NED) that's harder. 

To what extent can the details of the matching process (e.g. 1" vs 1.5") explain why the SDSS redshifts weren't matched in the first place?

**Comment by mhardcastle** [comment]
It's certainly not just the offset -- I used 1.5 arcsec as a match radius but the vast majority of matches without existing spec-z are <0.5 arcsec offset.

**Comment by jrcallingham** [comment]
Yes. I also found the same redshifts as you did Martin. Also I found situations were a source was on the CasJobs SDSS spec-z list as a QSO but is not listed separately in the bulk QSO catalog (hence causing Ken to exclude them) but I think Ken sorted that situation out.

**Comment by mhardcastle** [comment]
Fixed in v1.1b, closing.
