### ISSUE TITLE
Duplicated source in optical and component catalogues

### ISSUE THREAD

**Issue by laraalegre** [mhardcastle/lgz#37]
I found one duplicated source in the optical catalogue (LOFAR_HBA_T1_DR1_merge_ID_optical_v1.0.fits):
Source Name ILTJ132633.10+484745.7. The match is the same (same AllWISE and objID) but the RA, DEC, major axis, etc, are slightly different. It is the same source selected from different mosaics.
This source also appears duplicated in the component catalogue (LOFAR_HBA_T1_DR1_merge_ID_v1.0.comp.fits).

**Comment by mhardcastle** [comment]
For reasons that I don't fully understand this does not seem to exist in the draft v1.1 catalogue. All objects with duplicate optical IDs will be fixed up before v1.1 is released.

**Comment by wndywllms** [comment]
This was the single duplicate source in Tim's catalogues. When the mosaic ID's changed it slipped through again because the duplicate is excluded based on moasic_ID. I noticed it after v1.0 and fixed for v1.1.
(commenting for completeness in case this comes up again)

**Comment by mhardcastle** [comment]
Aha. Thanks for clearing that up!

**Comment by twshimwell** [comment]
Yeh weird source that sits almost exactly between two mosaic centres. Even though the images are the same in the two mosaics, due to reprojection it sits closer to one mosaic centre in that mosaic and closer to the other mosaic centre in the other mosaic.
