### ISSUE TITLE
Multiple entries for a source in component catalogue

### ISSUE THREAD

**Issue by laraalegre** [mhardcastle/lgz#38]
On the component catalogue there is a source with 9 duplicated rows:
Component_Name  = ILTJ115037.81+465929.4

**Comment by mhardcastle** [comment]
Thanks. Seems to be related to a blend... I'll check it out.

**Comment by mhardcastle** [comment]
This is now a test case, see #39

**Comment by mhardcastle** [comment]
OK, this set of sources with identical RA and Dec and slightly different radio properties exists in the Gaussian catalogue, and so presumably it's a pybdsf issue; the catalogue code is doing the right thing given that that is the case.  Do we require component_names in the component catalogue to be unique? Why? And if so, how should we make them unique in this case?

**Comment by nudomarinero** [comment]
I think it would be very useful to have an unique column in the table that can be used as a primary key. This would allow us to use all the existing relational database machinery in an easy way. That means that the table joins would be straightforward, there will be no degeneration (which is usually a source of problems) identifying sources with just one column, and entering the tables into a relational database engine will be seamless (useful to distribute the data publicly in the future).

An alternative is to use a combination of "Component_Name" and the radio properties that vary (peak_flux, etc) as the primary key. Although this is possible, it makes table operations more challenging and prone to errors. Besides, I thing it is standard practice to have single column primary key identifiers in most public surveys if not all.

To make them unique, we could just add a letter at the end of the degenerated component names (starting from the A) to distinguish them.

**Comment by mhardcastle** [comment]
Your proposed solution breaks the correspondence between the component table and the PyBDSF (Gaussian) table, though. And I am pretty sure it is not consistent with IAU naming rules either.

**Comment by nudomarinero** [comment]
Yes, it would require to get the corresponding key in the PyBDSF (Gaussian) table. If we do not want to modify the PyBDSF table, it could be done with an additional ordered list/table of the same length that contains only the unique names. This list can be stacked to the PyBDSF table (for example with vstack in astropy or concat in pandas) to make it "joinable" with the components table.

About the [IAU naming rules](http://cds.u-strasbg.fr/vizier/Dic/iau-spec.htx), I think they can be considered ["subcomponents"](http://cds.u-strasbg.fr/vizier/Dic/subcomponents.htx) of the source. In this case, using a letter could be acceptable:
> If, at some stage, subcomponents or multiplicity of sources is recognized, the current practice is to name the subcomponents with letters or numerals such as W 51 A.

Finally, something to consider. Are they really components of the source? If the source is like a sum of all these Gaussians, this proposal could make sense. If this is a glitch of PyBDSF and they are small variations of the same source, we may just consider to pick the best one and avoid all the possible naming issues that we are discussing.

**Comment by mhardcastle** [comment]
I believe all of these are real components of the source, which PyBDSF has for reasons of its own decomposed into many Gaussians. I've checked and there are a few other examples of this in the Gaussian catalogue.

I think given that:
* this makes no difference to the final source catalogue
* it makes no difference to the ability to select all the components of a source from the component catalogue
* we are not currently trying to export the catalogue as a relational database
* any change would break the 1:1 relationship between names and co-ordinates that we have everywhere else in the catalogue

I don't propose to 'fix' this. It's easy to produce catalogues that have the properties that you want, and I'm happy for post-processing scripts that do this to be contributed to the repository.
