### ISSUE TITLE
Point Sources Missing Flux (cutoff) Near Edge of Survey Region

### ISSUE THREAD

**Issue by jrcallingham** [mhardcastle/lgz#4]
There a number of point sources that are cut off near the edge of the survey region. This means that their flux densities are underestimated and they look like peaked-spectrum sources. Need to think of a clever way of adding a flag or excising these sources from the catalogue. 

Below are the names of a few of the sources that are cutoff at the edge of the survey, causing them to be missing flux:

ILTJ151524.99+543046.0
ILTJ150319.52+454944.5
ILTJ142450.82+502655.3
ILTJ142342.77+524831.0
ILTJ141236.02+512257.8
ILTJ124236.50+562844.6
ILTJ114646.72+562353.2

**Comment by wndywllms** [comment]
I've added some code to check for these sources with 7c97d45edda5918ad457026a72190f7b020e398f. Basically it quickly checks if there are any nan pixels within Maj of each source (261 sources), and for those checks in more detail if there are *any* nan pixels within a mask defined by the pybdsf ellipse (179 sources). There are all found on the edges as they should be:
![flag_edge_sources](https://user-images.githubusercontent.com/2170761/35041107-82d91d76-fb7b-11e7-813a-fafb0c20ed8a.png)

These 179 will be flagged as artefacts and treated in the same way (i.e. removed from the source and component catalogues)

Note that two of the examples given above don't get selected in this way:
ILTJ114646.72+562353.2 is a small component that doesn't actually overlap the edge, but it is right next to a large one that is cut off and not even included in the catalogue (arguably an artefact, but for other reasons)
![image](https://user-images.githubusercontent.com/2170761/35041277-1cbe678e-fb7c-11e7-8432-76ef856cf1f7.png)
ILTJ141236.02+512257.8 is not actually on the edge but is in a really messy part of the mosaic (probably a separate issue)
![image](https://user-images.githubusercontent.com/2170761/35041306-344680c6-fb7c-11e7-8575-8f87db536190.png)

**Comment by jrcallingham** [comment]
Smart idea Wendy about looking for nan pixels in the pybdsf ellipse after using the major axis! Looks like it sensibly gets most of the edge cases (agreed the two examples that don't get flagged are problematic for other reasons). I will have a play and see if I can see if I can find any sources that slip through the code but should get caught. I will let you know if I find any but looks unlikely.

**Comment by mhardcastle** [comment]
Let us know what you find, Joe. Our idea is to fully remove these sources from all catalogues in the next catalogue release.

**Comment by jrcallingham** [comment]
Hi guys,

Had some time today to run some tests on this script. It appears to catch all the point sources that are cut off near the edge of the large mosaic. Great!

However, it does miss excluding heavily resolved sources that are cut off by the edge of the mosaic e.g: ILTJ122510.79+455955.5 and ILTJ122510.05+460000.4 (same source but pybdsf has split it in two):
![image](https://user-images.githubusercontent.com/7263019/35286931-83c84b22-0061-11e8-8186-908f3a4cd3f6.png). Other examples are ILTJ125725.79+561852.2  and ILTJ125726.89+561842.4.

This is a slightly different problem we should think about how to deal with? Do I remember Martin that you already had an idea how how to get rid of the resolved sources that were cut off by the edge?

**Comment by mhardcastle** [comment]
As far as I can remember my idea was basically what Wendy has implemented. I guess the issue here is that PyBDSF doesn't get the size of the source right and so then the mask we make doesn't overlap the edge?

**Comment by wndywllms** [comment]
These are cases where PyBDSF hasn't joined up sources that should be joined up. In both cases there is one pybdsf component that is getting flagged because it is on the edge, and the other just misses the edge. I've added a step to check if the flagged edge sources overlap (roughly) any other sources and flagged these. It picks up another 14 sources, all of which look like they should be flagged like this. (I did have to exclude the case where the edge source is very large as this was catching the large artefacts around very bright sources around 45" from the edge and then unnecessarily flagging the bright compact source)

Of course, it is still possible there are cases of isolated sources where PyBDSF gets the size wrong. Not sure what, if anything, we can do about that.

Also fixed 2 small but important bugs.

see 38f3a06067df6d3121b7e7ba8ca50d5059dfacdf

**Comment by jrcallingham** [comment]
Agreed. I think this is the best we can do and most of the horrible cases have been caught :)

**Comment by mhardcastle** [comment]
Wendy, can you confirm whether this is live in the general catalogue generation?

**Comment by wndywllms** [comment]
Yes, it's live so I'm closing this now.
