### ISSUE TITLE
missing ID's for 3 2MASX sources

### ISSUE THREAD

**Issue by wndywllms** [mhardcastle/lgz#42]
3 ID_flag==2 sources in v1.1 were missing the 2MASX name in their ID_name so ended up with no ID

ILTJ105900.19+500255.0 2MASXJ10590015+5002557
ILTJ123201.77+462057.2 2MASXJ12320182+4620528
ILTJ140921.74+490217.9 2MASXJ14092132+4902197

(fixed in 60ddc4a3627b42763aa0bef81d5b2e15d537ca9d)

**Comment by wndywllms** [comment]
and further fix in b2cc6728006193d81e013a122c6d050262b3aa90 for v1.2

**Comment by wndywllms** [comment]
these all now have their ID_ra and ID_dec in my v1.2 merged catalogue

but one of them comes out with no ID_ra, ID_dec after the merge with PS1/wise 
ILTJ123201.77+462057.2 2MASXJ12320182+4620528
The PS/wise match is 5.30978" away so it misses the 5" cutoff

It's now the only ID_flag==2 source with no ID_ra, ID_dec

![iltj123201 77 462057 2](https://user-images.githubusercontent.com/2170761/40848964-957bbf4a-65b8-11e8-8c6e-4deb7b4f5c5c.png)

@mhardcastle thoughts? though may be for v1.next

**Comment by mhardcastle** [comment]
Manually edit its RA and Dec so it matches the PS catalogue entry and rerun everything? (or not...)

**Comment by wndywllms** [comment]
Ok, hardcoded a fix for it's RA, DEC. My latest v1.2 catalogue on the cluster has this fix, if you want to rerun your matching steps...

**Comment by mhardcastle** [comment]
Should be done and in the version of the catalogue on the release site.

**Comment by wndywllms** [comment]
fixed in v1.2
