### ISSUE TITLE
Missing artefacts?

### ISSUE THREAD

**Issue by nudomarinero** [mhardcastle/lgz#43]
We have found some PyBDSF sources (52; in LOFAR_HBA_T1_DR1_catalog_v0.9.srl.fixed.fits) that are in the PyBDSF catalogue but do not appear either in the artefact list (LOFAR_HBA_T1_DR1_merge_ID_v1.1.art.fits) or in the components table (they are neither components nor "deblended_from" sources in LOFAR_HBA_T1_DR1_merge_ID_v1.1b.comp.fits). 

We think that these sources may be perhaps artefacts that are missing from the artefact table. The number is very low but, if that is they are true artefacts, they could be added to the artefact list for consistency.

The list of PyBDSF Source_Names is:
[diff_sources.csv.txt](https://github.com/mhardcastle/lotss-catalogue/files/1943552/diff_sources.csv.txt)

**Comment by wndywllms** [comment]
@mhardcastle I think these are mostly flagged as artefacts in the blend stage which means my code doesn't know about them (I can feed it a list of them so we at least get a complete artefact list, or your blend code needs to append to the list of artefacts)

I can pick up 39 of them based on a check for 'Flagged' in the blend files in /data/lofar/mjh/hetdex_v4/blend/
(but this gets 6 extra sources that are in the final catalogues either as sources or components)

Another 3 are components of an lgz association that is flagged as a blend

The remaining 10 are a bit strange, in that they all only have a single component in their blend files.

**Comment by mhardcastle** [comment]
Fixed in v1.2 and a test added to the test suite to catch this (now that we have an official artefact list).
