### ISSUE TITLE
Broken sources

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/lgz#44]
Here's a place to submit IDs of sources where the catalogued association seems wrong.

ILTJ131451.56+542820.5

**Comment by mhardcastle** [comment]
ILTJ110552.82+552739.7 (lobe should be associated)

**Comment by mhardcastle** [comment]
ILTJ123803.85+531614.7 could use a check.

**Comment by bmingo** [comment]
ILTJ104543.54+525016.4 seems to have a bad association too. One of the components from a non-associated source is included, the other excluded (see attached image, my flood-filling algorithm masks out unassociated components, but goes a bit mad on this source). 
Edit: It is also possible that the pybdsf region associated with the source at the bottom is a bit too large and overlaps with the extended emission from the source at the top.
![3_a1_iltj104543 54 525016 4_map](https://user-images.githubusercontent.com/31618589/40751719-523db080-6464-11e8-9dd2-5a0dcc0d89a5.png)

**Comment by mhardcastle** [comment]
ILTJ105430.20+542507.4 (done)

ILTJ111159.05+485700.2 (done)

**Comment by mhardcastle** [comment]
@bmingo I've checked and the second of your two possibilities is the correct one. Can't really fix this in the catalogue. You could scale up the masks round unassociated sources a bit?

**Comment by mhardcastle** [comment]
All sources above should be fixed up in v1.2.
