### ISSUE TITLE
Lack of w3Mag and w4Mag errors

### ISSUE THREAD

**Issue by mahatmav** [mhardcastle/lgz#46]
Seems to be a lot of missing absolute w3Mag and w4Mag errors in LOFAR_HBA_T1_DR1_merge_ID_optical_v1.1b_restframe.fits.

This seems to occur only for sources with absolute mags > 17, and strangely errors are only missing where the corresponding w3Flux = 0, but the w3Flux errors do actually exist. This is the same case for w4 mags.

**Comment by bmingo** [comment]
I believe those are upper limits, or at least measurements below 5 sigma
