### ISSUE TITLE
sources with ID_names of 2MASS instead of 2MASX J 

### ISSUE THREAD

**Issue by wndywllms** [mhardcastle/lgz#47]
The referee noticed that there are a few sources  with ID_names of 2MASS instead of 2MASX J 

There are indeed 4 of these... all have ID_flag = [31,32] I think they get the 2MASS name in processing the hostbrokenup sources but my merging code is not dealing with them correctly their components are not already associated with any/the same 2MASX source

**Comment by mhardcastle** [comment]
Think this was fixed.
