### ISSUE TITLE
Truncated mosaic names

### ISSUE THREAD

**Issue by nudomarinero** [mhardcastle/lgz#49]
Same issue as #27 in the final (v1.2) catalogue.

In the final catalogue, the values of 'Mosaic_ID' are sometimes truncated to 8 characters. The width of the column is 11 but we can find the mosaics with long names truncated to 8 characters in some cases. For example, it is possible to find "P10Hetde" and "P10Hetdex" to refer to the same mosaic.

Fortunately, there is no degeneration in the truncated values and the original mosaic name can always be recovered from the truncated version. For the public release I think we should at least add a warning about this problem.

**Comment by twshimwell** [comment]
I thought v0.999 of the raw pybdsf catalogue was used to create v1.2 -- this version shouldnt have truncated names...

Perhaps an older version of the raw pybdsf catalogue was used?

**Comment by wndywllms** [comment]
Thought we'd fixed this :-/

@mhardcastle I see that all these sources with Mosaic_ID==P..Hetde have deblended ID_flags. Could be something in the deblending code?
