### ISSUE TITLE
Naming of optical IDs

### ISSUE THREAD

**Issue by mhardcastle** [mhardcastle/lgz#6]
The ID_name column in the final catalogue is useful but inconsistent about its naming of sources depending on where they came from. Should probably be rewritten in a standard form after merging.

**Comment by wndywllms** [comment]
For the ML sources I need to change the PSO and SDSS names from objID to the actual names. I guess for LGZ the PSO source names come from some version of the panstarrs catalogue (but not the merged wise/panstarrs photo-z catalogue because that's only got an objID)?

For the LGZ-zoom sources, there're a few called 'AllWISEN/A' (and no PSO ones).
And presumably the ones without a prefix coming out of the regular LGZ should be AllWISE.

**Comment by jcroston** [comment]
Related to this issue: some the sources called AllWISEN/A also don't have ID_ra and ID_dec values in the catalogue (others do, so this doesn't apply to all the ALLWISEN/A sources). These *do* have a ML_LR value, and so there must be a valid ID but for some reason the coords are missing

**Comment by mhardcastle** [comment]
So I think what we should do here is at the end (after the LGZ and ML catalogues are merged and everything has an optical ID crossmatch) is homogenize the naming of optical IDs. That's harder to screw up then doing it in several (currently three) different pieces of code. I'd put this in `fixup_topcat_merge.py` (which might want to be named something more descriptive but is basically the post-merger tidy up).

Wendy, do you agree?

**Comment by mhardcastle** [comment]
(The sources Jude mentions look to me like they just don't have a counterpart in Ken's catalogue despite having a ML value. This is a separate problem and should be raised as a separate issue.)

**Comment by wndywllms** [comment]
> So I think what we should do here is at the end (after the LGZ and ML catalogues are merged and everything has an optical ID crossmatch) is homogenize the naming of optical IDs. That's harder to screw up then doing it in several (currently three) different pieces of code. I'd put this in fixup_topcat_merge.py (which might want to be named something more descriptive but is basically the post-merger tidy up).
> Wendy, do you agree?

Yes, makes sense.

It may be helpful if Ken can include the panstarrs objName column in the panstarrs/wise phot-z catalogue

**Comment by mhardcastle** [comment]
Presumably it would be fine to generate a PSO J... name here based on the co-ordinates?

**Comment by wndywllms** [comment]
Shouldn't they match exactly to whatever name/designation/objName column exists in the catalogue from which they come (to facilitate exact value matching on a single column instead position matching) so how it is written will depend on where the match comes from. so we have e.g.

2MASX J10445443+5129301 -- annoyingly 2MASX designations don't have decimal points
AllWISE J124713.12+471921.3
PSO J122043.110+495010.214
SDSS JHHMMSS.ss+DDMMSS.s

So in principle fine to generate a PSO J... name, **but** (and maybe I am doing something wrong) I cannot always generate the exact panstarrs objName  from their raMean and decMean (on a random sample from http://archive.stsci.edu/panstarrs/search.php)

**Comment by mhardcastle** [comment]
In that case you're right and we're going to have to ask Ken to propagate these names (or get them back from the PS/WISE catalogues). Bother.

(Maybe the PS people don't quite follow the IAU convention either...)

**Comment by dunkenj** [comment]
Downloading the official PS1 objName catalog now so I can fold these in with the updated redshifts this week.

**Comment by mhardcastle** [comment]
That's great. We'll wait for those before taking any further action on this.

**Comment by mhardcastle** [comment]
OK, I have Ken's catalogue which has either an AllWISE or PSO ID for everything. So I propose that after the crossmatch we replace the ID_name with PSO if it exists, AllWISE if not (the reasoning being that PS has better resolution). Is there any argument for using anything else, e.g. 2MASX sources, @wllwen007 ?

**Comment by wndywllms** [comment]
Great. Yes, that makes sense. 

I think the only reason for keeping the few 2MASX/SDSS names I have is to record that they somehow got identified with a large optical galaxy (therefor potentially the source has bad photometry/phot-z), but this is encoded in the ID_flag (=2 for these sources) so that should suffice.

**Comment by mhardcastle** [comment]
OK, for now I am leaving them untouched iff ID_flag==2, but fixing them otherwise.

**Comment by mhardcastle** [comment]
Closing this, reopen if there are problems.
