### ISSUE TITLE
Isl_ID

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/lgz#7]
Isl_ID was in the radio catalogue but is missing from Isl_ID the value added catalogue. I thought we were going to keep this one as perhaps useful for complex sources in the same island.

**Comment by mhardcastle** [comment]
I'm struggling a bit to think what we might use it for?

**Comment by twshimwell** [comment]
OK perhaps not so useful and not needed then.

(looking back at emails it seems perhaps it was kept in the radio catalogue as it gives an indication that these are complex sources but maybe not needed in a final catalogue then).

**Comment by mhardcastle** [comment]
Well, it's easy to keep in for simple pybdsf sources if we can think of a use case. But of course it doesn't make sense for sources formed out of multiple pybdsf sources like the galaxy zoo ones. Let's keep this open for a bit in case someone comes up with a use case.

**Comment by mhardcastle** [comment]
I think we can close this -- nothing else has been suggested. Isl_id is in the component catalogue so you can reconstruct it (or them) for a given source.
