### ISSUE TITLE
New masking columns

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/lgz#8]
Ive nearly finished making two new columns

Number_Pointings -- Number of pointings that are mosaiced together that contain the source (takes account of the astronomic blanking too) 
Number_Masked -- Number of the above pointings in which the source is masked.

Do we want these in the final catalogue do you think? It does give an insight into the deconvolution but its a bit tricky as e.g. I just use the catalogued RA and DEC and also doesnt reflect in anyway the distances from the various pointing centres.

I dont think we need to try to expand it to take into account the full sizes of sources (users can look at the residual mosaics for these). But I suppose I could change  to have e.g. fraction of source weight deconvolved that is masked (so summing up all the weight images with an without masks). Then we probably would only need that column rather than two new columns.

**Comment by mhardcastle** [comment]
Yeah, I was thinking the deconvolved weight fraction would be the right measure, because then we don't get alarming figures for sources that are right at the edge of one field and right in the centre for another. Though we can keep the other two columns for the moment too, perhaps. They might be useful for the paper.

Then maybe this information wants to go not in the source catalogue but in the annotated component catalogue we're making (an example of which is now on the data release site). It's easy enough to go from one to the other.

**Comment by twshimwell** [comment]
OK, ill add in that column too.

**Comment by twshimwell** [comment]
(im doing it on LOFAR_HBA_T1_DR1_catalog_v0.9.srl.fixed.fits)

**Comment by mhardcastle** [comment]
Yep that's fine. The comment about what catalogue it goes on was more me thinking aloud than anything you need to worry about!

**Comment by twshimwell** [comment]
These are ready if you like them.

**Comment by mhardcastle** [comment]
Oh yes, you sent them before and it got buried. Don't suppose you'd like to produce a version that keeps the DC_* columns as well, so we can kill two birds with one stone? Then we can re-make the catalogues based on that.

**Comment by twshimwell** [comment]
sure

**Comment by mhardcastle** [comment]
These columns are now present in the components catalogue.

**Comment by mhardcastle** [comment]
... but we have decided we need to do this with the Gaussian catalogue, so don't use the v0.4 values.

**Comment by twshimwell** [comment]
I now have a masked gaussian catalogue but havent yet merged it through to the source catalogue.

**Comment by mhardcastle** [comment]
These masked fractions are now in the final catalogue so, other than being a bit concerned that they are rather lower than we would hope, I guess we can close this.
