### ISSUE TITLE
Source_Name 's

### ISSUE THREAD

**Issue by wndywllms** [mhardcastle/lgz#9]
The Source_Name has the form ILTJHHMMSS.ss+DDMMSS.s (*except some earlier iteration of the catalouge that has ILTJHHMMSS.sss+DDMMSS.ss) but I think we may still have this a bit wrong.

Names are derived from the coordinates as follows:
```
ilt=[]
sc=SkyCoord(t['RA'],t['DEC'],frame='icrs')
strings=sc.to_string(style='hmsdms',sep='',precision=2)
for s in strings:
    ilt.append(str('ILTJ'+s).replace(' ','')[:-1])
```
(as in https://github.com/mhardcastle/lotss-catalogue/blob/master/utils/fix_sourceid.py)

So *truncated* to 1 d.p. in DEC (after rounding to 2 dp) and *rounded* to 2 d.p. in RA

The IAU convention to truncate is rather annoying: http://cdsweb.u-strasbg.fr/Dic/iau-spec.html#S3.2.1
but I think we shouldn't be truncating to N d.p.'s after rounding to N+1 d.p.'s.

Also we should have a space between ILT and J.

**Comment by mhardcastle** [comment]
I felt when I wrote that code that what we do is good enough given that we don't know any position to sub-arcsec precision... but happy to fix this if others disagree.

However I think it would be an awful lot of effort to do so _internally_ before the catalogue release. Perhaps rewriting at release time might be worthwhile.

**Comment by mhardcastle** [comment]
Ok, we could think about this one now...

- inserting the space in ILT J... is easy and can be done at the final pass over the catalogue
- we could also rewrite all the source names, but if we do we break the mapping between what we call the sources internally (e.g. in the zoom lists) and what we call them externally, which is going to be annoying.

Preferences, @wllwen007 ?

**Comment by mhardcastle** [comment]
I am thinking this ship may have sailed since we have released a couple of versions of the catalogue that have the old format. Names with spaces in would be a pain for all the filenames that are based on source names that we use in the catalogue processing. Let's leave it as it is.
